import {
    FileText,
    Link,
    FolderOpen,
    Star,
    Home,
    Search,
    Settings,
    User,
    Users,
    Bell,
    MessageCircle,
    Trash,
    Edit,
    Save,
    Download,
    Upload,
    Camera,
    Image,
    Play,
    Pause,
    StopCircle,
    Check,
    X,
    Plus,
    Minus,
    RefreshCw,
    LogOut,
    LogIn,
    Cloud,
    Calendar,
    Heart,
    Bookmark,
    Tag,
    FolderPlus,
    FolderMinus,
    FilePlus,
    FileMinus,
    AlertTriangle,
    Info,
    HelpCircle,
    Share,
    Lock,
    Unlock,
    Eye,
    EyeOff,
    Menu,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
    'file-text': FileText,
    'link': Link,
    'folder': FolderOpen,
    'star': Star,
    'home': Home,
    'search': Search,
    'settings': Settings,
    'user': User,
    'users': Users,
    'bell': Bell,
    'message': MessageCircle,
    'trash': Trash,
    'edit': Edit,
    'save': Save,
    'download': Download,
    'upload': Upload,
    'camera': Camera,
    'image': Image,
    'play': Play,
    'pause': Pause,
    'stop': StopCircle,
    'check': Check,
    'x': X,
    'plus': Plus,
    'minus': Minus,
    'refresh': RefreshCw,
    'log-out': LogOut,
    'log-in': LogIn,
    'cloud': Cloud,
    'calendar': Calendar,
    'heart': Heart,
    'bookmark': Bookmark,
    'tag': Tag,
    'folder-plus': FolderPlus,
    'folder-minus': FolderMinus,
    'file-plus': FilePlus,
    'file-minus': FileMinus,
    'alert': AlertTriangle,
    'info': Info,
    'help': HelpCircle,
    'share': Share,
    'lock': Lock,
    'unlock': Unlock,
    'eye': Eye,
    'eye-off': EyeOff,
    'menu': Menu,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    // Add more icons as needed
};

// Helper function to get icon component
export function getIconByName(name: string): LucideIcon {
    return iconMap[name] || FileText  // Return FileText as fallback
}